### PR TITLE
Added "Clip That" functionality

### PR DESCRIPTION
**Pull request by linkian209**
This patch adds channel clipping functionality. The action will call the Twitch clipping endpoint, then it will post a message containing the clip url to the selected channel's chat.

### CODE REVIEW

**Comment by linkian209** [comment]
As a note to the maintainers of the token server, the OAuth will need to also request the `clips:edit` scope for this action to work out of the box.

**Comment by thedist** [comment]
This is not compatible with the revamp that is being worked on that completely reworks the API section, as well as the entire auth process.

**Comment by linkian209** [comment]
Thanks for the reply!

Do you have a branch for the API revamp? I recently started using this software and this is a functionality I would love to have for my streams. I’ll do the rework you suggest as well as make up a template action that just posts the clip as is.

**Comment by thedist** [comment]
The revamp is in a private branch, due to some of it currently being under NDA.

The main focus of the revamp has been to switch the auth to DCF, so it's handled entirely within the Companion module, reworked how API requests are handled so the GOT dependency can be removed, more API endpoints have been added and the actions/feedback/variables from those endpoints, and some EventSub Websockets support.

Due to the significant layoffs at Twitch early this year it has delayed progress to some degree as priorities shifted, but we hope to have the module ready for testing near the end of Q3, with release in Q4.

**Pull request closed without merging**
